name: fake_http_client
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.4

dev_dependencies:
  checks: ^0.3.0
  dart_code_metrics_presets: ^2.17.0
  dio: ^5.7.0
  test: ^1.24.0
